---
urls_file: urls.txt
bookmarks_html_file: bookmarks.html
timeout: 60
log_file: bookmark.log
log_level: DEBUG
rewrite_url: true
sleep: 3000
random_sleep: true
headers:
  - name: Accept
    value: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8
  - name: Accept-Encoding
    value: gzip, deflate, br, zstd
  - name: Accept-Language
    value: en-US,en;q=0.9
  - name: Cache-Control
    value: max-age=0
  - name: Referer
    value: https://www.google.com/
  - name: User-Agent
    value: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/130.0.0.0 Safari/537.36
